name: build-and-verify-intunewin

on:
  workflow_dispatch:
    inputs:
      app:
        description: Target application
        required: true
        type: choice
        options:
          - chrome
          - slack
          - warp
          - zoom

jobs:
  build_and_verify:
    # 共通ロジックを呼び出す
    uses: ./.github/workflows/_core-build.yml
    with:
      app: ${{ inputs.app }}
